### ISSUE TITLE
How to define target heading for all projects?

### ISSUE THREAD

**Issue by labe-me** [colonelpanic8/org-project-capture#28]
Hello, I'd like to target an heading inside a file,

I have my ~/Notes/work.org file which contains many things including a "* Projects " entry which should receive the content generated by org-projectile.

Is it possible?

Thank you!

**Comment by IvanMalison** [comment]
It should be pretty easy to make this possible

**Comment by IvanMalison** [comment]
Hey @labe-me This is now possible in the big-changes branch (https://github.com/IvanMalison/org-projectile/tree/big-changes). Would you mind checking that out and seeing if it works for you?

**Comment by PrestanceDesign** [comment]
Hi,

The branch big-changes doesn't exists anymore...was it merged ?

Best regards.

**Comment by IvanMalison** [comment]
@PrestanceDesign yeah, althoguh, I think that you would need to write a little bit of code to get this to work.

**Comment by kingyakshaver** [comment]
I'd like this also
