### ISSUE TITLE
commit 7ab90ac breaks org-projectile-goto-location-for-project 

### ISSUE THREAD

**Issue by thanhvg** [colonelpanic8/org-project-capture#46]
7ab90ac made change to `occ-capture-goto-marker` but it breaks `org-projectile-goto-location-for-project`.

Now `org-projectile-goto-location-for-project` which uses `occ-capture-goto-marker` won't switch to org buffer anymore but opens it it background.

**Comment by Lenbok** [comment]
`7ab90ac` was reverted, so this can be closed?
