### ISSUE TITLE
Adding all project-specfic files to org-agenda-files

### ISSUE THREAD

**Issue by singpolyma** [colonelpanic8/org-project-capture#48]
I tried to use the snippet in the README, but quickly found org complaining that many of the files did not exist (since not every folder on my computer with a .git contains a TODO.org).  Additionally, every time I reload my config I found that it would add copies of the files to the list again.  This snippet I'm using now may be a more complete suggestion for the README:

```
	(setq org-agenda-files (seq-filter 'file-readable-p (delete-dups (append org-agenda-files (org-projectile-todo-files)))))
```

**Comment by colonelpanic8** [comment]
@singpolyma Adding all org files is done by design, because if you do this type of filtering, you wont get todos from the new files when a new org files is created after emacs starts.

Seems like confusing behavior.
