### ISSUE TITLE
Set :immediate-finish to true? 

### ISSUE THREAD

**Issue by chuckberrypi** [colonelpanic8/org-project-capture#49]
I have the following setup code to make it so that I can capture the text from a comment in my project to the Projectile to-do item:
```
(defun get-annotation ()
  (plist-get org-store-link-plist :annotation))

(defun remove-starting-brackets (s)
  (require 'subr-x)
  (string-remove-prefix "\[\[" s))

(defun remove-trailing-brackets (s)
  (require 'subr-x)
  (string-remove-suffix "\]\]" s))

(defun remove-brackets (s)
  (remove-trailing-brackets (remove-starting-brackets s)))

(defun description-text ()
  (remove-trailing-brackets
    (nth 1 
      (split-string (get-annotation) ";;"))))

(setq org-projectile-capture-template 
      "* TODO %? %(description-text)\n [[%(remove-brackets (get-annotation))][%f]]")
```

As suggested in the title, I would like to set :immidiate-finish to true so that this just captures automatically. Is that possible? In the alternative, is it possible to create several projectile templates? 

Thanks for the great package!

**Comment by colonelpanic8** [comment]
@chuckberrypi functions like `org-project-capture-project-todo-completing-read` and `org-project-capture-capture-for-current-project take arbitrary additional options`

e.g. `(org-project-capture-project-todo-completing-read :immediate-finish t)` does the immediate finish that you seem to be asking for.

if you just want a normal capture template, you can just pass that argument like this:

```
(org-project-capture-project-todo-entry :immediate-finish t)
```
