### ISSUE TITLE
Can't use from a magit buffer

### ISSUE THREAD

**Issue by Lenbok** [colonelpanic8/org-project-capture#58]
Sometimes I'm in a magit buffer (e.g. status or log) and would like to capture a project TODO. When I try this, I get:
`org-projectile-project-root-of-filepath: Wrong type argument: stringp, nil`

I'm using the following capture template:
```
  (add-to-list 'org-capture-templates
               (org-projectile-project-todo-entry
                :capture-template "* TODO %?\n"
                :capture-character "p"
                :capture-heading "Project TODO"))
```

**Comment by IvanMalison** [comment]
Hmmmm. Seems to work for me.

Can you give some more details?

**Comment by Lenbok** [comment]
I don't particular understand the org capture stuff, but from what I can see/guess it'll try and set the `:category` property in the `occ-context` by calling `(org-projectile-category-from-file (org-capture-get :original-file))` but the `:original-file` property of `org-capture-plist` is nil (presumably since a magit buffer doesn't have a backing file). I wonder how it could possibly work for you?

**Comment by Lenbok** [comment]
I do think it has worked in the past, so maybe there's been an update to either org or magit that makes this work differently?

**Comment by colonelpanic8** [comment]
@Lenbok okay, taking a look at this hopefully today

**Comment by colonelpanic8** [comment]
@Lenbok should be fixed now
