### ISSUE TITLE
adding a todo and goto a project does not work (projectile backend)

### ISSUE THREAD

**Issue by tokstokstoks** [colonelpanic8/org-project-capture#62]
I am currently using your last package (dated august 17 2023) with Doom Emacs via WSL2 (Windows 10).
I use the projectile backend with the `org-project-capture-single-file option` enabled

When I try to record a new todo for a project which is not listed in the todo file I get the following error:

`org-project-capture-get-project-todo-file: Wrong type argument: stringp, nil`

When the project is already listed in in the todo.org file it just creates a new * TODO under this project.

A second error arises when I want to go to a project via the todo.org file.

Then i get the following error: `eval: Symbol’s function definition is void: org-projectile-open-project`
I could not find this function in the code anymore (I use this todo file also on a linux machine with an older version of org-projectile).
I tried to rename the function in the link to:
`org-project-capture-open-project` but then I get this error:  `(org-project-capture-open-project "project_name") => nil`

Could it be that with the rewrite of org-project-capture these functions are not implemented yet for the projectile backend?

**Comment by colonelpanic8** [comment]
- @tokstokstoks I fixed a ton of issues last night. Are you sure you have the VERY latest version?
  > Could it be that with the rewrite of org-project-capture these functions are not implemented yet for the projectile backend?
No, although there were several issues last night, everything is theoretically complete
- Can you share the configuration you are using?

**Comment by colonelpanic8** [comment]
@tokstokstoks one thing I just noticed is that README instructions were actually slightly incorrect

They said to write
```
(defvar org-project-capture-backend
  (make-instance 'org-project-capture-project-backend))
```

when they should have said
```
  (setq org-project-capture-default-backend
    (make-instance 'org-project-capture-project-backend))
```

**Comment by tokstokstoks** [comment]
Your anwer got me in the right direction though it doesn't fully work yet.
I have the august 17 version of org-project-capture (20230817.816) and org-projectile (20230817.851) installed.

When I use the use-package method (doom emacs: use-package!) it almost works but only when I use the deprecated functions:

```perl
(use-package! org-project-capture
  :bind (("C-c v" . org-projectile-project-todo-completing-read))
  :config
  (defvar org-project-capture-default-backend
  (make-instance 'org-project-capture-projectile-backend)) 
  (setq org-project-capture-projects-file "/mnt/c/Users/myusername/org/todo.org")
  (org-projectile-single-file)
  :ensure t)

```
I can select a project from the project list when using `org-projectile-project-todo-completing-read`.
In case of:
- a new project in the todo file it creates a new project with a new todo.
- an existing project it creates a new todo under the selected project.

The goto function does __not__ work (pressing the project name).
This gives the following error: `(org-project-capture-open-project "nameofproject") => nil`

When I try the code snippet with the 'new' variable names from the readme I cannot select a project as the project list is emtpy.

```perl
(require 'org-project-capture)
(use-package! org-project-capture
  :bind (("C-c v" . org-project-capture-project-todo-completing-read))
  :config
  (defvar org-project-capture-default-backend
  (make-instance 'org-project-capture-projectile-backend))  
  (setq org-project-capture-projects-file "/mnt/c/Users/myusername/org/todo.org")
  (org-project-capture-single-file 
  :ensure t)
```

The setq method somehow does not work with make-instance combined and gives the following error: `(void-function make-instance)`. 
Without `make-instance` the following code does work the same way as the first described use-package method:

```perl
(setq org-project-capture-default-backend 'org-project-capture-projectile-backend)
(setq org-project-capture-projects-file "/mnt/c/Users/myusername/org/todo.org")
(global-set-key (kbd "C-c v") 'org-projectile-project-todo-completing-read)
(org-projectile-single-file)

```
Still I get the error: `(org-project-capture-open-project "nameofproject") => nil` when I goto a project in my todo.org file via the project name.

**Comment by colonelpanic8** [comment]
This:

```
  (defvar org-project-capture-default-backend
  (make-instance 'org-project-capture-projectile-backend))
  ```
  
  needs to be setq, not defvar. The variable is already defined.

you should check what the current value of `org-project-capture-default-backend` is. I would suspect it is the project backend, not the projectile backend.

**Comment by colonelpanic8** [comment]
This `(setq org-project-capture-default-backend 'org-project-capture-projectile-backend)`

definitely will not work. You need it to be an instance, not a symbol.

`(org-projectile-single-file) `only affects the  deprecated org-projectile functions. You need to use the equivalent org-project-capture function.






> The setq method somehow does not work with make-instance combined and gives the following error: `(void-function make-instance)`.

That's really strange. I don't know, maybe try (require 'eieio), but that doesn't really make sense because requring org-project-capture should have already made that happen.

However, I will say that this:

```
(use-package! org-project-capture
  :bind (("C-c v" . org-project-capture-project-todo-completing-read))
  :config
  (defvar org-project-capture-default-backend
  (make-instance 'org-project-capture-projectile-backend))  
  (setq org-project-capture-projects-file "/mnt/c/Users/myusername/org/todo.org")
  (org-project-capture-single-file 
  :ensure t)
  ```

looks kind of malformed to me.

if your configure section spans multiple statments, you're usually going to need a progn.

Here is a cleaned up version:

```
(use-package! org-project-capture
  :bind (("C-c v" . org-project-capture-project-todo-completing-read))
  :ensure t
  :config
  (progn
    (setq org-project-capture-default-backend
          (make-instance 'org-project-capture-projectile-backend))
    (setq org-project-capture-projects-file "/mnt/c/Users/myusername/org/todo.org")
    (org-project-capture-single-file)))
```

**Comment by tokstokstoks** [comment]
Thanks for your extensive answer. I'm still a beginner at perl. After reading about progn adding it looks like the way to go indeed.
I did a copy/paste the snippet from your readme which does not have progn included.
The use-package snippet in the readme still states defvar. Could it be that you forgot to change that part to setq?

I made some progress. I use your cleaned up version and I now get the following error: `cl-no-applicable-method: No applicable method: make-instance, org-project-capture-projectile-backend
` 
I have no clue why I get a different error, probably I need a break.

I Still have to bind the keys to `org-projectile-project-todo-completing-read` otherways the projectlist is empty.

Changing the statement to: `(setq org-project-capture-default-backend
          (make-instance 'org-project-capture-project-backend))` does not create an error anymore concerning make-instance / org-project-capture-projectile-backend.

Obviously I want to use the projectile backend but it seems like something goes wrong with the initialization of org-project-capture-projectile-backend.

Do you perhaps have an idea?

**Comment by colonelpanic8** [comment]
> I made some progress. I use your cleaned up version and I now get the following error: `cl-no-applicable-method: No applicable method: make-instance, org-project-capture-projectile-backend `

do you get this value on initialization? evaluation of the use-package statement...

**Comment by colonelpanic8** [comment]
Oh wait, I see the issue.

You still need to use org-projectile

This is what my config looks like:

```
(use-package org-project-capture
  :bind ("C-c o p" . org-project-capture-project-todo-completing-read)
  ;; We want this to load somewhat quickly because we need to update the list of agenda files
  :defer 2
  :config
  (progn
    (use-package org-projectile
      :demand t
      :config
      (setq org-project-capture-default-backend
            (make-instance 'org-project-capture-projectile-backend)))
    (setq org-project-capture-strategy
          (make-instance 'org-project-capture-combine-strategies
                         :strategies (list (make-instance 'org-project-capture-single-file-strategy)
                                           (make-instance 'org-project-capture-per-project-strategy))))
    (setq org-project-capture-projects-file
          (imalison:join-paths imalison:org-dir "projects.org")
          org-project-capture-capture-template
          (format "%s%s" "* TODO %?" imalison:created-property-string))
    (add-to-list 'org-capture-templates
                 (org-project-capture-project-todo-entry
                  :capture-character "l"
                  :capture-heading "Linked Project TODO"))
    (add-to-list 'org-capture-templates
                 (org-project-capture-project-todo-entry
                  :capture-character "p"))
    (setq org-confirm-elisp-link-function nil)
    (imalison:add-to-org-agenda-files (org-project-capture-todo-files))))
```

See how I have a separate use package for org-projectile?

You're going to need that now. org-project-capture does not include the projectile backend.

**Comment by colonelpanic8** [comment]
@tokstokstoks See the linked commit in 

https://github.com/colonelpanic8/org-project-capture/issues/60

(https://github.com/colonelpanic8/org-project-capture/commit/4ca2667d498fa259772e46ff5e101285446d70b6)

This was just fixed last night. you may need to get an updated version.

**Comment by colonelpanic8** [comment]
@tokstokstoks as far as I understand it, this was simply a configuration error on your end. closing, but feel free to reopen if you think theres an underlying issue.
